apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poc-redis
  name: poc-redis
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: poc-redis
  type: ClusterIP
status:
  loadBalancer: {}